package fifa

import (
	go_fifa "github.com/ImDevinC/go-fifa"
)

var eventsToSkip = map[go_fifa.MatchEvent]bool{
	go_fifa.Substitution: true,
	go_fifa.MatchPaused:  true,
	go_fifa.MatchResumed: true,
	go_fifa.GoalAttempt:  true,
	go_fifa.Offside:      true,
	go_fifa.CornerKick:   true,
	go_fifa.FreeKickPost: true,
	go_fifa.ShotBlocked:  true,
	go_fifa.Foul:         true,
	go_fifa.CoinToss:     true,
	go_fifa.Unknown3:     true,
	go_fifa.ThrowIn:      true,
	go_fifa.Clearance:    true,
	go_fifa.Unknown2:     true,
	go_fifa.Crossbar:     true,
	go_fifa.FoulUnknown:  true,
	go_fifa.GoalieSaved:  true,
	go_fifa.Unknown:      true,
	go_fifa.DroppedBall:  true,
	go_fifa.Assist:       true,
}

var flagEmojis = map[string]string{
	"ALB": ":flag-al:",
	"ARG": ":flag-ar:",
	"AUS": ":flag-au:",
	"BEL": ":flag-be:",
	"BRA": ":flag-br:",
	"CAN": ":flag-ca:",
	"CHI": ":flag-cl:",
	"CHN": ":flag-cn:",
	"CMR": ":flag-cm:",
	"COL": ":flag-co:",
	"CRC": ":flag-cr:",
	"CRO": ":flag-hr:",
	"DEN": ":flag-dk:",
	"ECU": ":flag-ec",
	"EGY": ":flag-eg:",
	"ENG": ":flag-england:",
	"ESP": ":flag-es:",
	"FRA": ":flag-fr:",
	"GER": ":flag-de:",
	"GHA": ":flag-gh:",
	"IRN": ":flag-ir:",
	"ISL": ":flag-is:",
	"ITA": ":flag-it:",
	"JAM": ":flag-jm:",
	"JPN": ":flag-jp:",
	"KOR": ":flag-kr:",
	"KSA": ":flag-sa:",
	"MAR": ":flag-ma:",
	"MEX": ":flag-mx:",
	"NED": ":flag-nl:",
	"NGA": ":flag-ng:",
	"NOR": ":flag-no:",
	"NZL": ":flag-nz:",
	"PAN": ":flag-pa:",
	"PER": ":flag-pe:",
	"POL": ":flag-pl:",
	"POR": ":flag-pt:",
	"QAT": ":flag-qa:",
	"RSA": ":flag-za:",
	"RUS": ":flag-ru:",
	"SCO": ":flag-scotland:",
	"SEN": ":flag-sn:",
	"SRB": ":flag-rs:",
	"SUI": ":flag-ch:",
	"SWE": ":flag-se:",
	"THA": ":flag-th:",
	"TUN": ":flag-tn:",
	"URU": ":flag-uy:",
	"USA": ":flag-us:",
	"WAL": ":flag-wales:",
	"ZAF": ":flag-za:",
}
