package fifa

import (
	"fmt"
	"strings"

	go_fifa "github.com/imdevinc/go-fifa"
)

var eventNameToValue = map[string]go_fifa.MatchEvent{
	"GoalScore":        go_fifa.GoalScore,
	"Assist":           go_fifa.Assist,
	"YellowCard":       go_fifa.YellowCard,
	"RedCard":          go_fifa.RedCard,
	"DoubleYellow":     go_fifa.DoubleYellow,
	"Substitution":     go_fifa.Substitution,
	"PenaltyAwarded":   go_fifa.PenaltyAwarded,
	"MatchStart":       go_fifa.MatchStart,
	"HalfEnd":          go_fifa.HalfEnd,
	"MatchPaused":      go_fifa.MatchPaused,
	"MatchResumed":     go_fifa.MatchResumed,
	"GoalAttempt":      go_fifa.GoalAttempt,
	"FoulUnknown":      go_fifa.FoulUnknown,
	"Offside":          go_fifa.Offside,
	"CornerKick":       go_fifa.CornerKick,
	"ShotBlocked":      go_fifa.ShotBlocked,
	"Foul":             go_fifa.Foul,
	"CoinToss":         go_fifa.CoinToss,
	"Unknown3":         go_fifa.Unknown3,
	"DroppedBall":      go_fifa.DroppedBall,
	"ThrowIn":          go_fifa.ThrowIn,
	"Clearance":        go_fifa.Clearance,
	"MatchEnd":         go_fifa.MatchEnd,
	"Unknown2":         go_fifa.Unknown2,
	"HitCrossbar":      go_fifa.HitCrossbar,
	"HitPost":          go_fifa.HitPost,
	"OwnGoal":          go_fifa.OwnGoal,
	"HandBall":         go_fifa.HandBall,
	"FreeKickGoal":     go_fifa.FreeKickGoal,
	"PenaltyGoal":      go_fifa.PenaltyGoal,
	"FreeKickCrossbar": go_fifa.FreeKickCrossbar,
	"FreeKickPost":     go_fifa.FreeKickPost,
	"GoalieSaved":      go_fifa.GoalieSaved,
	"PenaltyMissed":    go_fifa.PenaltyMissed,
	"PenaltyMissed2":   go_fifa.PenaltyMissed2,
	"VARPenalty":       go_fifa.VARPenalty,
	"Hydration":        go_fifa.Hydration,
	"Pending":          go_fifa.Pending,
}

func ParseEventNames(names []string) (map[go_fifa.MatchEvent]bool, error) {
	skipSet := make(map[go_fifa.MatchEvent]bool, len(names))
	var unknown []string
	for _, name := range names {
		val, ok := eventNameToValue[strings.TrimSpace(name)]
		if !ok {
			unknown = append(unknown, name)
			continue
		}
		skipSet[val] = true
	}
	if len(unknown) > 0 {
		return skipSet, fmt.Errorf("unknown event name(s): %s", strings.Join(unknown, ", "))
	}
	return skipSet, nil
}

var flagEmojis = map[string]string{
	"AFG": ":flag-af:",
	"AIA": ":flag-ai:",
	"ALB": ":flag-al:",
	"ALG": ":flag-dz:",
	"AND": ":flag-ad:",
	"ANG": ":flag-ao:",
	"ARG": ":flag-ar:",
	"ARM": ":flag-am:",
	"ARU": ":flag-aw:",
	"ASA": ":flag-as:",
	"ATG": ":flag-ag:",
	"AUS": ":flag-au:",
	"AUT": ":flag-at:",
	"AZE": ":flag-az:",
	"BAH": ":flag-bs:",
	"BAN": ":flag-bd:",
	"BDI": ":flag-bi:",
	"BEL": ":flag-be:",
	"BEN": ":flag-bj:",
	"BER": ":flag-bm:",
	"BFA": ":flag-bf:",
	"BHR": ":flag-bh:",
	"BHU": ":flag-bt:",
	"BIH": ":flag-ba:",
	"BLR": ":flag-by:",
	"BLZ": ":flag-bz:",
	"BOL": ":flag-bo:",
	"BOT": ":flag-bw:",
	"BRA": ":flag-br:",
	"BRB": ":flag-bb:",
	"BRU": ":flag-bn:",
	"BUL": ":flag-bg:",
	"CAM": ":flag-kh:",
	"CAN": ":flag-ca:",
	"CAY": ":flag-ky:",
	"CGO": ":flag-cg:",
	"CHA": ":flag-td:",
	"CHI": ":flag-cl:",
	"CHN": ":flag-cn:",
	"CIV": ":flag-ci:",
	"CMR": ":flag-cm:",
	"COD": ":flag-cd:",
	"COL": ":flag-co:",
	"COM": ":flag-km:",
	"COK": ":flag-ck:",
	"CPV": ":flag-cv:",
	"CRC": ":flag-cr:",
	"CRO": ":flag-hr:",
	"CTA": ":flag-cf:",
	"CUB": ":flag-cu:",
	"CUW": ":flag-cw:",
	"CYP": ":flag-cy:",
	"CZE": ":flag-cz:",
	"DEN": ":flag-dk:",
	"DJI": ":flag-dj:",
	"DMA": ":flag-dm:",
	"DOM": ":flag-do:",
	"ECU": ":flag-ec:",
	"EGY": ":flag-eg:",
	"ENG": ":flag-england:",
	"EQG": ":flag-gq:",
	"ERI": ":flag-er:",
	"ESP": ":flag-es:",
	"EST": ":flag-ee:",
	"ETH": ":flag-et:",
	"FIJ": ":flag-fj:",
	"FIN": ":flag-fi:",
	"FRA": ":flag-fr:",
	"FRO": ":flag-fo:",
	"GAB": ":flag-ga:",
	"GAM": ":flag-gm:",
	"GEO": ":flag-ge:",
	"GER": ":flag-de:",
	"GHA": ":flag-gh:",
	"GIB": ":flag-gi:",
	"GRE": ":flag-gr:",
	"GRN": ":flag-gd:",
	"GUA": ":flag-gt:",
	"GUI": ":flag-gn:",
	"GNB": ":flag-gw:",
	"GUM": ":flag-gu:",
	"GUY": ":flag-gy:",
	"HAI": ":flag-ht:",
	"HKG": ":flag-hk:",
	"HON": ":flag-hn:",
	"HUN": ":flag-hu:",
	"IDN": ":flag-id:",
	"IND": ":flag-in:",
	"IRL": ":flag-ie:",
	"IRN": ":flag-ir:",
	"IRQ": ":flag-iq:",
	"ISL": ":flag-is:",
	"ISR": ":flag-il:",
	"ITA": ":flag-it:",
	"JAM": ":flag-jm:",
	"JOR": ":flag-jo:",
	"JPN": ":flag-jp:",
	"KAZ": ":flag-kz:",
	"KEN": ":flag-ke:",
	"KGZ": ":flag-kg:",
	"KOR": ":flag-kr:",
	"KOS": ":flag-xk:",
	"KSA": ":flag-sa:",
	"KUW": ":flag-kw:",
	"LAO": ":flag-la:",
	"LBN": ":flag-lb:",
	"LBR": ":flag-lr:",
	"LBY": ":flag-ly:",
	"LCA": ":flag-lc:",
	"LES": ":flag-ls:",
	"LIE": ":flag-li:",
	"LTU": ":flag-lt:",
	"LUX": ":flag-lu:",
	"LVA": ":flag-lv:",
	"MAC": ":flag-mo:",
	"MAD": ":flag-mg:",
	"MAR": ":flag-ma:",
	"MAS": ":flag-my:",
	"MDA": ":flag-md:",
	"MDV": ":flag-mv:",
	"MEX": ":flag-mx:",
	"MKD": ":flag-mk:",
	"MLI": ":flag-ml:",
	"MLT": ":flag-mt:",
	"MNE": ":flag-me:",
	"MNG": ":flag-mn:",
	"MOZ": ":flag-mz:",
	"MRI": ":flag-mu:",
	"MSR": ":flag-ms:",
	"MTN": ":flag-mr:",
	"MWI": ":flag-mw:",
	"MYA": ":flag-mm:",
	"NAM": ":flag-na:",
	"NCA": ":flag-ni:",
	"NCL": ":flag-nc:",
	"NED": ":flag-nl:",
	"NEP": ":flag-np:",
	"NGA": ":flag-ng:",
	"NIG": ":flag-ne:",
	"NIR": ":flag-gb:",
	"NOR": ":flag-no:",
	"NZL": ":flag-nz:",
	"OMA": ":flag-om:",
	"PAK": ":flag-pk:",
	"PAN": ":flag-pa:",
	"PAR": ":flag-py:",
	"PER": ":flag-pe:",
	"PHI": ":flag-ph:",
	"PLE": ":flag-ps:",
	"PNG": ":flag-pg:",
	"POL": ":flag-pl:",
	"POR": ":flag-pt:",
	"PRK": ":flag-kp:",
	"PUR": ":flag-pr:",
	"QAT": ":flag-qa:",
	"ROU": ":flag-ro:",
	"RSA": ":flag-za:",
	"RUS": ":flag-ru:",
	"RWA": ":flag-rw:",
	"SAM": ":flag-ws:",
	"SCO": ":flag-scotland:",
	"SDN": ":flag-sd:",
	"SEN": ":flag-sn:",
	"SEY": ":flag-sc:",
	"SGP": ":flag-sg:",
	"SKN": ":flag-kn:",
	"SLE": ":flag-sl:",
	"SLV": ":flag-sv:",
	"SMR": ":flag-sm:",
	"SOL": ":flag-sb:",
	"SOM": ":flag-so:",
	"SRB": ":flag-rs:",
	"SRI": ":flag-lk:",
	"SSD": ":flag-ss:",
	"STP": ":flag-st:",
	"SUI": ":flag-ch:",
	"SUR": ":flag-sr:",
	"SWE": ":flag-se:",
	"SVK": ":flag-sk:",
	"SVN": ":flag-si:",
	"SWZ": ":flag-sz:",
	"SYR": ":flag-sy:",
	"TAH": ":flag-pf:",
	"TAN": ":flag-tz:",
	"TCA": ":flag-tc:",
	"THA": ":flag-th:",
	"TGA": ":flag-to:",
	"TJK": ":flag-tj:",
	"TLS": ":flag-tl:",
	"TOG": ":flag-tg:",
	"TPE": ":flag-tw:",
	"TRI": ":flag-tt:",
	"TUN": ":flag-tn:",
	"TUR": ":flag-tr:",
	"TKM": ":flag-tm:",
	"UGA": ":flag-ug:",
	"UKR": ":flag-ua:",
	"UAE": ":flag-ae:",
	"URU": ":flag-uy:",
	"USA": ":flag-us:",
	"UZB": ":flag-uz:",
	"VAN": ":flag-vu:",
	"VEN": ":flag-ve:",
	"VGB": ":flag-vg:",
	"VIE": ":flag-vn:",
	"VIN": ":flag-vc:",
	"VIR": ":flag-vi:",
	"WAL": ":flag-wales:",
	"YEM": ":flag-ye:",
	"ZAF": ":flag-za:",
	"ZAM": ":flag-zm:",
	"ZIM": ":flag-zw:",
}
