name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24.3"
      - name: Go test
        run: go test -v ./...
