name: Deploy changes

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    name: Build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Make dist
        run: make dist
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        working-directory: terraform
        run: terraform init
      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve