name: Deploy changes

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          patchAll: true
          token: ${{ github.token }}
          branch: main
      - name: Make dist
        run: VERSION=${{ steps.semver.outputs.next }} make dist
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: false
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        working-directory: terraform
        run: terraform init
      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve